#!/bin/sh

cd apache-storm-0.9.3
java -classpath lib/*:../squall-core/target/squall-0.2.0.jar ch.epfl.data.squall.main.Main ../test/squall_plan_runner/confs/local/0_01G_sketchmin > zkm.out 2> zkm.err &
# tail -f zkm.out

